# Generated by Django 4.2 on 2023-05-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('roll', models.CharField(default=None, max_length=50, null=True)),
                ('cgpa', models.FloatField(default=None, null=True)),
                ('advisor', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
    ]
