# Generated by Django 4.2 on 2023-05-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='uid',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
