# Generated by Django 4.2 on 2023-05-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0002_students_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='uid',
            new_name='password',
        ),
        migrations.AddField(
            model_name='students',
            name='username',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
