# Generated by Django 4.2 on 2023-05-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tt', '0002_delete_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=None, max_length=50, null=True)),
                ('teachers_id', models.CharField(default=None, max_length=50, null=True)),
                ('fullname', models.CharField(default=None, max_length=50, null=True)),
                ('password', models.CharField(default=None, max_length=50, null=True)),
                ('department', models.CharField(default=None, max_length=500, null=True)),
            ],
        ),
    ]
